### ISSUE TITLE
Profile requires update 

### ISSUE THREAD

**Issue by hybtoy** [ultrahorizon/UH-VPN-Docs#48] opened 2020-09-28 17:07 UTC
Hello team!

I have just added profile to UH VPN Android application with OTP password. Profile imported successfully but when I press connect button, it tells me "Profile requires update". Is there anyway to check application log?
![IMG_20200928_220344.jpg](https://user-images.githubusercontent.com/12900872/94463820-fcbff600-01d6-11eb-8d56-973e4e323e8a.jpg)

**Comment by AnthonyWharton** [comment] 2020-09-28 19:42
Hi @hybtoy,

Sorry that's a very rare message! Something has gone wrong between the app recieving the VPN profile and passing it to the VPN service that runs in a different part of the OS.

In terms of resolving this, if you force close the app by swiping it away in your recent apps screen, clear the notification and then restart the app, does the connect button then work? 

If not, try go to your phone's system settings and find the relevant VPN settings menu [1] and then try forget UH VPN and then perform the same force close and restart procedure. 

---

If you could answer a few questions for me that would be great to try ensure that this doesn't happen again or for anyone else.
 1. Can I double check that you are on the latest version of the app (2.0.3)
 1. Did this occur for you straight after syncing a new profile to the device, or has this happened to an existing profile (perhaps between an update)?

Thanks!

---

[1] The VPN settings will appear in different locations on different skins of Android, but is usually under Network Settings/may be an advanced setting - using your system settings' search functionality and searching for "VPN" should be a safe bet if you are unsure.

**Comment by AnthonyWharton** [comment] 2020-09-28 19:48
I should have added, simply switching between profiles should also resolve this - however if you've only got one profile this might not be possible and you'll need to try the steps above.

(In the case of only having one profile you could remove the profile and quickly press undo to reapply it, but I would not recommend this as if you get interrupted or your phone freezes you might loose your profile!)

**Comment by hybtoy** [comment] 2020-09-29 04:19
Hi @AnthonyWharton, 

I have updated app to version 2.0.3 but it didn't help, same notification. 

I have tried all steps above but it didn't help me, still same notification.

> I should have added, simply switching between profiles should also resolve this

Yes, this helped me but if I will have to do this to all android devices, I will have huge bill from UH-VPN :D

**Comment by AnthonyWharton** [comment] 2020-09-29 05:47
Thanks for the update @hybtoy. Glad it is resolved.  Please can I ask you to try a few things for me to see if we can narrow this down, as this error shouldn't happen at all and it would be good to know what caused it.

First off, is this reproducible; If you get a chance and remove the profile on the device (resetting it to the original state before you had the issue) and also remove it from the management page - then recreate it.  Do you get the same message when attempting to add the profile again?

If you do, I also had a realisation that simply changing server should resolve this issue - if you don't have more than one server you can also try push a make a small change to the server, such as the name of it, and then reopen the app. Any changes to the server, or switching between them, should reapply to profile to the VPN Service.

Finally, if you could list your make and model of Android Device, along with Android Version that would be very helpful. Thanks!

**Comment by hybtoy** [comment] 2020-09-29 05:58
> First off, is this reproducible; If you get a chance and remove the profile on the device (resetting it to the original state before you had the issue) and also remove it from the management page - then recreate it. Do you get the same message when attempting to add the profile again?

Yes.
Steps: 
1. Revoke existing profile
2. Add new one (same person)
3. Add profile with OTP to device.
4. Trying to connect but it tells me that "Profile requires update".
5. I have removed UH VPN service but it didn't help.

> If you do, I also had a realisation that simply changing server should resolve this issue - if you don't have more than one server you can also try push a make a small change to the server, such as the name of it, and then reopen the app. Any changes to the server, or switching between them, should reapply to profile to the VPN Service.

Yes, this helped me. 

My device:

Redmi Note 8 Pro - Android 10. https://www.gsmarena.com/xiaomi_redmi_note_8_pro-9812.php

**Comment by AnthonyWharton** [comment] 2020-09-29 06:12
Brilliant, I'll cross reference those steps with the code and see if I can get it to reproduce on my side - sorry about that, I haven't seen this message since early development when I still hadn't finished implementing the app properly!

Could I also ask, did you have any valid (selected on the main screen) or invalid (e.g. revoked or expired) profiles on your device before you synced the new one?

**Comment by hybtoy** [comment] 2020-09-29 06:21
> Could I also ask, did you have any valid (selected on the main screen) or invalid (e.g. revoked or expired) profiles on your device before you synced the new one?

No, I revoked the old profile first, deleted it and add new one.

**Comment by hybtoy** [comment] 2020-09-29 06:37
I have recorded a video of steps. This time I didn't delete revoked profile.
The bug reproduced again, I had to change the server name to be able to connect to server.

**Comment by AnthonyWharton** [comment] 2020-09-29 07:13
If you revoke a device and then add a new one you won't be charged any more, e.g.

- Group has 10 devices -> Billed for 10 devices at the end of the month.
- Group revokes 1 device leaving 9 devices -> Billed for 10 devices at the end of the month
- Group issues 1 device making 10 devices again -> Billed for 10 devices at the end of the month.

You're billed for the maximum usage that month - Sorry I should have made that crystal clear at the start!

I'll take a look at the video and get back to you, thanks so much for your cooperation :)

**Comment by jwsi** [comment] 2020-09-29 07:49
@hybtoy, if you delete all of your "test" devices from the web interface, I'll ensure that they're removed from your invoice this month. Can you please let me know when you've done this so that i know how much to discount 👍

**Comment by AnthonyWharton** [comment] 2020-09-29 10:32
I can confirm that I can reproduce this bug now and will hopefully have a fix done by the end of today (plus Google Play review times).

**Comment by AnthonyWharton** [comment] 2020-10-01 11:33
This has been fixed in the new 2.0.4 release, available now on the Play Store!

**Closed by AnthonyWharton** 2020-10-01 11:33 UTC
Labels: active, android, bug
