### ISSUE TITLE
BUG: Can't add profile code to UH-VPN client on Windows 10

### ISSUE THREAD

**Issue by nasiriyima** [ultrahorizon/UH-VPN-Docs#37] opened 2020-07-09 20:19 UTC
**Can't Add Profile code sent via email to UH-VPN Client on Windows 10 Version 10.0.18362 Build 18362**
Created a new profile/device on UH-VPN but unable to add code to client on device.

**To Reproduce**
1. Create a new client on UH-VPN admin
2. Logged into email and downloaded VPN-Client for windows and copied code
3. Installed UH-VPN client on client machine
4. and tried to add new client using the code received and copied from email

**Expected behavior**
UH-VPN Client refusing to add client without any error message

**Screenshots**
![screen](https://user-images.githubusercontent.com/8083679/87086614-be471a80-c229-11ea-8da2-6aa98718ce86.PNG)

**Application (please complete the following information):**
 - Device: HP
 - OS: Windows 10
 - Version 10.0.18362 Build 18362

**Comment by jwsi** [comment] 2020-07-09 20:21
@AnthonyWharton I think this one is for you to investigate.

**Comment by AnthonyWharton** [comment] 2020-07-09 21:02
Hi @nasiriyima,

Thanks for trying UH VPN! Sorry you've run into this issue, it looks like something has gone wrong even making the request. I have a few questions/requests for you so that we can work to get this solved for you.

 1) Can I please confirm you are on UH VPN 1.0.2? (Open UH VPN from the tray and press About)
 2) When you press the "Add Profile" button, does anything happen at all? (Normally, the text field should grey out and the manage profiles window will have a loading spinner)
 3) Finally, would you be happy to send me some diagnostic information via email?  _No personal/sensitive information is included in this and it will only be used for debugging purposes._ **Instructions:**
    1) Please close UH VPN if it is open already by clicking on the tray icon and pressing quit.
    2) Please open UH VPN again, then open the "Manage Profiles" window, press the plus button and attempt to add the following OTP code: _"abc"_.
    2) Upon failure, please then try to add your actual OTP code.
    3) Please close UH VPN by clicking on the tray icon and pressing quit.
    4) Press and hold the Windows Key and press R at the same time.
    5) In the "Run" dialog that appears, please copy and paste in the following command: `%PROGRAMFILES%\Ultra Horizon\UH VPN\CollectDiagnostics.bat`
    6) Please follow the instructions it provides and it will generate a file for you on your desktop called `uh-vpn-diagnostics.7z`.  Please email that to me: `anthony -at- ultra-horizon.com`

I'll look into this for you in the meantime and await your email if you are happy to help with that, and then get back to you with some further steps as soon as possible.

**Comment by nasiriyima** [comment] 2020-07-09 21:22
@AnthonyWharton @jwsi Thank you all for the prompt response and below are the answers to you questions
1. Yes! I can confirm I am using UH VPN 1.0.2
2. No, Nothing appeared
3. Sure
 **Note:** After following your instructions from (i) to (iii) the client was added successfully and I was able to connect. I have sent you the diagnostics information to your email

**Comment by nasiriyima** [comment] 2020-07-09 21:26
On Thursday, 9 July 2020, 22:02:51 GMT+1, Anthony Wharton <notifications@github.com> wrote:  
 
 


Hi @nasiriyima,

Thanks for trying UH VPN! Sorry you've run into this issue, it looks like something has gone wrong even making the request. I have a few questions/requests for you so that we can work to get this solved for you.
   
   - Can I please confirm you are on UH VPN 1.0.2? (Open UH VPN from the tray and press About)
   - When you press the "Add Profile" button, does anything happen at all? (Normally, the text field should grey out and the manage profiles window will have a loading spinner)
   - Finally, would you be happy to send me some diagnostic information via email? No personal/sensitive information is included in this and it will only be used for debugging purposes. Instructions:      
      - Please close UH VPN if it is open already by clicking on the tray icon and pressing quit.
      - Please open UH VPN again, then open the "Manage Profiles" window, press the plus button and attempt to add the following OTP code: "abc".
      - Upon failure, please then try to add your actual OTP code.
      - Please close UH VPN by clicking on the tray icon and pressing quit.
      - Press and hold the Windows Key and press R at the same time.
      - In the "Run" dialog that appears, please copy and paste in the following command: %PROGRAMFILES%\Ultra Horizon\UH VPN\CollectDiagnostics.bat
      - Please follow the instructions it provides and it will generate a file for you on your desktop called uh-vpn-diagnostics.7z. Please email that to me: anthony -at- ultra-horizon.com


I'll look into this for you in the meantime and await your email if you are happy to help with that, and then get back to you with some further steps as soon as possible.

**Comment by AnthonyWharton** [comment] 2020-07-09 21:29
That’s great to hear you’re up and running! I just got your email so I’ll take a look through it now, but for now I’ll close this issue. 

This is a pretty illusive bug that if is the one I’m thinking of has even stumped engineers from Qt (one of the frameworks we use to make UH VPN)! Hopefully it should happen again, but if it does I’d appreciate it if you could comment here to let me know!

If you have any further problems feel free to reopen it or file a new issue :)

Have a great day!

**Comment by nasiriyima** [comment] 2020-07-09 21:51
@AnthonyWharton Hope the engineers are able to fix the issue on time, because I'm just trying out your VPN to implement in a larger setup that will involve more users and my deadline is on Monday & so far so good I'm impressed with your response time to opened issues. Even though I have further questions that I need clarified. Thus, I don't know if it is possible to chat with a technical customer support team to answer some of my questions on your website or if you can point me to any forums, I will really appreciate it.

Do have a great day as well! Thanks!

**Comment by AnthonyWharton** [comment] 2020-07-09 22:06
You’re speaking with the lead developer for the apps, so I hope you’re in good hands or I’m doing something wrong!

We’ve only ever had this issue come up once in development, and now with you, so unless your users are on identical setups as you I believe it should be pretty rare/non-existent to come up again! I’ll be looking into it properly tomorrow for you. In any case, you should now be aware that a restart often fixes the problem, and  that once profiles are synced once they are always usable with the VPN core (the network code for the VPN and profile syncing is separate).

If you ever have any issues this is your best place to post them, we’re always active here 👍

**Comment by jwsi** [comment] 2020-07-09 22:46
Hi @nasiriyima,

With regards to questions on the website, you can either open up issues here for a quick response, or alternatively if it's sales related give us a call on +44 117 200 1107 Option 1 and we'll be able to discuss any web interfaces questions you have.

James.

**Comment by nasiriyima** [comment] 2020-07-10 07:45
Hi @AnthonyWharton 
No, you are not doing anything wrong. Sorry about that! I guess my question came a bit in a wrong context. You actually did a great job, I only thought some of the questions I will be asking may not be appropriate here. Since, my guess is you may only want to discuss application related issues on here while my questions are targeted towards configuration and usage in my current required scenario. But If you are OK with my questions here, its fine by me. Below are some of the questions I have that I need clarified;
1.  I need to allow users on the VPN to access only resources meant to be accessed through the VPN without them going through the VPN for personal web or network activities. For Example, I will like users to be able to access a web application at www.portal.com through the VPN. But if they want to go to www.google.com, that traffic shouldn't go through the VPN. Is it possible to achieve this even on the premium version?

2. Is there a way I can block the computers on the same VPN network from communicating with each other while connected to the VPN Network?

@jwsi 
Thanks! I will keep those handy and above are my questions.

**Comment by jwsi** [comment] 2020-07-10 09:52
Hi @nasiriyima,

Here are the answers to your questions above.

1. This can easily be accomplished via the "split tunnelling" feature on the premium plan. In the server settings you'd turn off the "Redirect all IPv4 Traffic" and "Redirect all IPv6 Traffic" switches, add `156.151.59.19/32` to the custom IPv4 routes (this is the A record of www.portal.com from `dig a www.portal.com`) and blank out IPv6 routes. Then only traffic to www.portal.com will be routed over the VPN. Please note that the system will set DNS servers from the VPN, so if you choose 1.1.1.1 and 1.0.0.1, those will be used by clients, but DNS traffic will **not** be sent over the VPN unless you specify `1.1.1.1/32` and `1.0.0.1/32` in the custom IPv4 routes too. For more info on split tunnelling see our [split routing guide](https://docs.uh-vpn.com/en/latest/website/servers/split-routing.html).

2. This can be achieved by adding custom forwarding rules instead of the default UH VPN rules. By default UH VPN will insert the following rules:

`iptables --append FORWARD -s <ipv4_tunnel_network> -j ACCEPT`
`ip6tables --append FORWARD -s <ipv6_network> -j ACCEPT`

This has the effect of forwarding all traffic anywhere on the VPN subnet. If you wished to block inter-client communication, simply disable the "Add forwarding rules" button on the server settings and instead add a rule from a shell such as:

`iptables --append FORWARD -s 172.31.255.0/24 -d 172.31.255.1 -j ACCEPT`

Modify the above example to suit your tunnel network and server address. UH VPN will take the first usable address as the server address so if you have a tunnel network of `192.168.0.0/24`, then the server address to use in the above rule would be `192.168.0.1`.

This rule will only allow communication from VPN clients to the VPN server. All other communication between clients will be blocked.

**Comment by jwsi** [comment] 2020-07-10 10:20
Please see updated rules ^ - I made a mistake...

**Comment by nasiriyima** [comment] 2020-07-10 13:08
@jwsi I will review and revert test and revert. Thanks for the assist!

**Comment by jwsi** [comment] 2020-07-10 13:15
@nasiriyima no problem! If you have any issues let me know.

**Comment by nasiriyima** [comment] 2020-07-10 18:10
@jwsi It all worked!!! Thank you very much for the assist, I really appreciate it. But I still have one more question. Will the IP table rule be persisted on server restart?

**Comment by jwsi** [comment] 2020-07-10 22:05
Hi @nasiriyima,

Glad to hear it worked! 😊

The iptables rules above will not persist across reboots and you'll have to execute the above rules on boot unless you do the following:

Use a package called `iptables-persistant`

`sudo apt install iptables-persistent`
`sudo /etc/init.d/iptables-persistent save`

Then if you update the rules in future simply use `iptables-save` to keep the rules file up to date.

**Comment by AnthonyWharton** [comment] 2020-07-14 14:35
Just wanted to update you and say that I've identified this bug now and am working on a fix which will be included in the 1.0.3 update :)

**Comment by hybtoy** [comment] 2020-07-14 20:04
> Hi @nasiriyima,
> 
> Here are the answers to your questions above.
> 
> 1. This can easily be accomplished via the "split tunnelling" feature on the premium plan. In the server settings you'd turn off the "Redirect all IPv4 Traffic" and "Redirect all IPv6 Traffic" switches, add `156.151.59.19/32` to the custom IPv4 routes (this is the A record of www.portal.com from `dig a www.portal.com`) and blank out IPv6 routes. Then only traffic to www.portal.com will be routed over the VPN. Please note that the system will set DNS servers from the VPN, so if you choose 1.1.1.1 and 1.0.0.1, those will be used by clients, but DNS traffic will **not** be sent over the VPN unless you specify `1.1.1.1/32` and `1.0.0.1/32` in the custom IPv4 routes too. For more info on split tunnelling see our [split routing guide](https://docs.uh-vpn.com/en/latest/website/servers/split-routing.html).
> 
> 2. This can be achieved by adding custom forwarding rules instead of the default UH VPN rules. By default UH VPN will insert the following rules:
> 
> `iptables --append FORWARD -s <ipv4_tunnel_network> -j ACCEPT`
> `ip6tables --append FORWARD -s <ipv6_network> -j ACCEPT`
> 
> This has the effect of forwarding all traffic anywhere on the VPN subnet. If you wished to block inter-client communication, simply disable the "Add forwarding rules" button on the server settings and instead add these rules from a shell:
> 
> `iptables --append FORWARD -s 172.31.255.0/24 -d 172.31.255.0/24 -j DROP`
> `iptables --append FORWARD -s 172.31.255.0/24 -j ACCEPT`
> 
> Modify the above example to suit your tunnel network. These rules will drop inter-client communication.
> 

I think this has to be added to FAQ or docs site.

**Comment by AnthonyWharton** [comment] 2020-07-14 20:28
Thanks for the suggestion @hybtoy, we’ll start collecting these useful answers and add them to the docs site! 

I’m general, if we see answers getting reactions we will do this without question, but occasionally questions are quite specific and we don’t want to make it too overwhelming and people should be able to search the issues page for specific problems!

**Comment by nasiriyima** [comment] 2020-07-23 09:29
@AnthonyWharton @jwsi 
Hi,
So everything is set and running for production and unfortunately one of the users just encountered a problem. Initially the user was able to setup the client and connected successfully. But after a while the UH-VPN client stopped working. I had to connect remotely to the client's computer using Teamviewer (since we are not in the same area) to diagnose the issue, which was strange. Whenever you try to run the UH-VPN application nothing happens, and the icon is not showing up in the the taskbar tray of the computer. When I checked the process, I could see that a UH-VPN client process was created and running. But I couldn't see the app anywhere. I have generated a diagnosis file and sent it to @AnthonyWharton's email and attached below is image of the windows task manage processes showing the UH-VPN process running. 
![process](https://user-images.githubusercontent.com/8083679/88271113-9dbd9c80-ccce-11ea-9fb7-b508c594499d.PNG)

System Information
 Windows 10 Pro Version 10.0.19041 Build 19041

**Comment by AnthonyWharton** [comment] 2020-07-23 09:43
Thanks for the email, I have just replied to you directly, if we could communicate there for this as it is likely not related to this issue that would be great.  For the benefit of others looking around the UH VPN issue tracker, I will edit this post with the solution when we get to it, however for now:

From the screenshot it looks like the "UH VPN Windows Daemon" isn't running, could you please go to the "Services" tab and ensure that `"uh-vpn-daemon"` is "Running".. If not right click on it and press "Start" to attempt to start it.

If the daemon is not in the services list then the best option to try uninstall and reinstall UH VPN.

**Comment by jwsi** [comment] 2020-07-26 16:18
For reference the above unrelated sub-issue is now solved and was caused by two things:

1. DNS servers were specified as subnets instead of raw IPs. E.g. 1.1.1.1/32 instead of 1.1.1.1
2. Multiple incorrect iptables rules were conflicting with one another

**Comment by jwsi** [comment] 2020-07-26 23:48
> > Hi @nasiriyima,
> > Here are the answers to your questions above.
> > 
> > 1. This can easily be accomplished via the "split tunnelling" feature on the premium plan. In the server settings you'd turn off the "Redirect all IPv4 Traffic" and "Redirect all IPv6 Traffic" switches, add `156.151.59.19/32` to the custom IPv4 routes (this is the A record of [www.portal.com](http://www.portal.com) from `dig a www.portal.com`) and blank out IPv6 routes. Then only traffic to [www.portal.com](http://www.portal.com) will be routed over the VPN. Please note that the system will set DNS servers from the VPN, so if you choose 1.1.1.1 and 1.0.0.1, those will be used by clients, but DNS traffic will **not** be sent over the VPN unless you specify `1.1.1.1/32` and `1.0.0.1/32` in the custom IPv4 routes too. For more info on split tunnelling see our [split routing guide](https://docs.uh-vpn.com/en/latest/website/servers/split-routing.html).
> > 2. This can be achieved by adding custom forwarding rules instead of the default UH VPN rules. By default UH VPN will insert the following rules:
> > 
> > `iptables --append FORWARD -s <ipv4_tunnel_network> -j ACCEPT`
> > `ip6tables --append FORWARD -s <ipv6_network> -j ACCEPT`
> > This has the effect of forwarding all traffic anywhere on the VPN subnet. If you wished to block inter-client communication, simply disable the "Add forwarding rules" button on the server settings and instead add these rules from a shell:
> > `iptables --append FORWARD -s 172.31.255.0/24 -d 172.31.255.0/24 -j DROP`
> > `iptables --append FORWARD -s 172.31.255.0/24 -j ACCEPT`
> > Modify the above example to suit your tunnel network. These rules will drop inter-client communication.
> 
> I think this has to be added to FAQ or docs site.

This has been added in changeset d1ff909cccd6315f4af85735d258c6437c92918a

**Comment by AnthonyWharton** [comment] 2020-08-05 14:49
Fixes will be included in the 1.0.3 update which is being worked on now and is due to be released in the coming weeks.

**Closed by AnthonyWharton** 2020-08-05 14:49 UTC
Labels: active, bug
